os: Visual Studio 2015

version: '{build}'

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

install:
  - cmd: choco install ant -y -f -i
  - cmd: refreshenv
  - cmd: set BUCK_EXTRA_JAVA_ARGS=-Djna.nosys=true
  - cmd: set GOROOT=
  - cmd: set PATH=%PATH:C:\go\bin;=%
  - cmd: set PATH=%PATH:C:\go\bin=%
  - cmd: set
  - cmd: python --version
  - cmd: java -version
  - cmd: ant -version


build_script:
  - "bin\\buck build buck"

test_script:
  - "bin\\buck test --all --test-selectors=@windows_failures.txt --test-selectors=@windows_cxx_support.txt"

artifacts:
  - path: buck-out\gen\programs\buck.pex
